### ISSUE TITLE
onDocumentEntered is never called

### ISSUE THREAD

**Issue by arhatbaid91** [imperiumlabs/GeoFirestore-Android#1]
I have cloned the example code but its not working. `onGeoQueryReady `is called directly, skipping `onDocumentEntered  `.

I have attached my database structure. Its basic but still if I may be messing up things there.

![capture](https://user-images.githubusercontent.com/19239996/43371410-03cbab42-9357-11e8-88cf-7b0c36e0d490.PNG)

**Comment by theonlynick0430** [comment]
Hey arhatbaid91,

Sorry to get back to you so late.

Your problem actually stems from your database structure, not the library
itself. The location of a document should be stored as follows:



Also, remember that you can always set the location of a document through
code.

Regards,
Nikhil Sridhar
