### ISSUE TITLE
What if the searched area is empty?

### ISSUE THREAD

**Issue by quebin31** [imperiumlabs/GeoFirestore-Android#10]
I can't handle the case whenever the search area is empty, or maybe I'm not seeing it, it's like there is a missing `onEmptyResult` or something like that.

**Comment by sanisloandras** [comment]
You should collect all your data in onDocumentEntered callback into some collection, until onGeoQueryReady is called.
`var isGeoQueryReady = false
val initialDocumentSnapshots = mutableListOf<DocumentSnapshot>()'

'override fun onGeoQueryReady() {
                    isGeoQueryReady = true
                    //check if initialDocumentSnapshots is empty
                }'

'override fun onDocumentEntered(p0: DocumentSnapshot, p1: GeoPoint?) {
                    if (isGeoQueryReady) {
                        ...
                    } else {
                        initialDocumentSnapshots.add(p0)
                    }
                }`

**Comment by Supercaly** [comment]
Closing because it's solved by the documentation
