### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by smithc42** [imperiumlabs/GeoFirestore-Android#12]
Not getting any data back in my GeoQueryDataEventListener. Is this library working/maintained?

**Comment by subrud** [comment]
No. I guess. There is a big issue regarding geoQueryAtLocation() and has been issued 3-4 times but developers ain't responding.

**Comment by theonlynick0430** [comment]
If you find an errors, please help contribute to the library by forking and adding a pull request. We will gladly approve them.

**Comment by Supercaly** [comment]
The code in github already resolve the issue, but the version 1.1.1 is not up to date and dosn't contain the fix.

**Comment by mirdones** [comment]
> If you find any errors, please help contribute to the library by forking and adding a pull request. We will gladly approve them.

@theonlynick0430 could you please release a new version of this library with the pull request fix?

**Comment by theonlynick0430** [comment]
Sorry for the inactivity. I just released a new version. Let me know if it still doesn't work.
