### ISSUE TITLE
error in geofirestore update location to firestore

### ISSUE THREAD

**Issue by zoro238** [imperiumlabs/GeoFirestore-Android#15]
view error

    java.lang.NoSuchMethodError: No virtual method set(Ljava/util/Map;Lcom/google/firebase/firestore/SetOptions;)Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/firestore/DocumentReference; or its super classes (declaration of 'com.google.firebase.firestore.DocumentReference' appears in /data/app/com.2.cvcvbb-2/base.apk)
        at org.imperiumlabs.geofirestore.GeoFirestore.setLocation(GeoFirestore.java:128)

**Comment by mirdones** [comment]
its is the same issue as #13
