### ISSUE TITLE
Failed to resolve: v1.2.0 and 1.2.0

### ISSUE THREAD

**Issue by Supercaly** [imperiumlabs/GeoFirestore-Android#18]
I have tried importing the new releases (with tag v1.2.0 and 1.2.0) and in both case i got this error from Gradle sync
``` 
ERROR: Failed to resolve: com.github.imperiumlabs:GeoFirestore-Android:v1.2.0
Show in Project Structure dialog
Affected Modules: app
```

**Comment by theonlynick0430** [comment]
I just made a new release with the latest merge. Please try again.

**Comment by zoro238** [comment]
could you explain more ...
Because the use of the Library many problems ..
We want to use it

**Comment by Supercaly** [comment]
Close because there is a new stable version (v1.4.0)
