### ISSUE TITLE
Build broken for v1.3.0

### ISSUE THREAD

**Issue by jobot0** [imperiumlabs/GeoFirestore-Android#23]
Hello ! 
I was trying to use the last version but the build for `v1.3.0` seems to be broken on jitpack

https://jitpack.io/com/github/imperiumlabs/GeoFirestore-Android/v1.3.0/build.log

```
> Task :geofirestore:compileReleaseJavaWithJavac FAILED
/home/jitpack/build/GeoFirestoreExample/geofirestore/src/main/java/org/imperiumlabs/geofirestore/GeoQuery.java:410: error: cannot find symbol
        Set<GeoHashQuery> newQueries = GeoHashQuery.queriesAtLocation(new GeoLocation(center.getLatitude(), center.getLongitude()), radius);
                                                   ^
  symbol:   method queriesAtLocation(GeoLocation,double)
  location: class GeoHashQuery
1 error

```

**Comment by scm573** [comment]
Same, currently we have to integrate everything by downloading the source code directly.

Hi @theonlynick0430, would you please take a look at the build?
Thank you very much.

**Comment by scm573** [comment]
OK so I just tried fixing the issue and sent a PR. You may try the build of my fork branch first:
```
implementation 'com.github.scm573:GeoFirestore-Android:work-SNAPSHOT'
```
You can browse the built artifacts here:
https://javadoc.jitpack.io/com/github/scm573/GeoFirestore-Android/work-SNAPSHOT

**Comment by Supercaly** [comment]
There is a new version (1.4.0)
` implementation 'com.github.imperiumlabs:GeoFirestore-Android:v1.4.0'`
