### ISSUE TITLE
Cannot find symbol class GeoQueryDataEventListener on 1.4.0

### ISSUE THREAD

**Issue by mirdones** [imperiumlabs/GeoFirestore-Android#30]
I have updated to 1.4.0 and now it can't find symbol class GeoQueryDataEventListener.

I am going back to 1.2.1 that was the last stable version that I could make work untill this is resolved.

**Comment by Supercaly** [comment]
Can you post more about the error? 
Post the part of the code, the error the IDE throws and all you can.

**Comment by mirdones** [comment]
There was an error on import.

It was needed to change:

import org.imperiumlabs.geofirestore.GeoQueryDataEventListener;

to:

import org.imperiumlabs.geofirestore.callbacks.GeoQueryDataEventListener;
