### ISSUE TITLE
ERROR: Failed to resolve: com.github.imperiumlabs:GeoFirestore-Android:v1.5.0

### ISSUE THREAD

**Issue by malebuffy** [imperiumlabs/GeoFirestore-Android#38]
I am using Android Studio 3.5.1
Gradle Build Version 3.5.1
Gradle Wrapper 5.6.4

and receive this when I try to Sync gradle files

```
ERROR: Failed to resolve: com.github.imperiumlabs:GeoFirestore-Android:v1.5.0
Show in Project Structure dialog
Affected Modules: app
```
Although I have done this

> allprojects {
>     repositories {
>         ...
>         maven { url 'https://jitpack.io' }
>     }
> }

and this

> implementation 'com.github.imperiumlabs:GeoFirestore-Android:v1.5.0'

**Comment by BikramKhanikar** [comment]
same problem

**Comment by BikramKhanikar** [comment]
Enable Jitpack
Add it in your root build.gradle at the end of repositories:

`allprojects {`
    `repositories {`
        `...`
        `maven { url 'https://jitpack.io' }`
   ` }`
`}`
