### ISSUE TITLE
Error when updating geoQuery.center

### ISSUE THREAD

**Issue by brendanosborne** [imperiumlabs/GeoFirestore-Android#4]
Hi Guys, I can't work this one out...

This works okay if the lat and lng don't change:
`geoQuery?.center = newLatLng`

If the lat and lng are different I am getting this error:

`java.lang.NullPointerException: Attempt to read from field 'com.google.firebase.firestore.ListenerRegistration org.imperiumlabs.geofirestore.GeoQuery$GeoHashQueryListener.childAddedListener' on a null object reference
`
It looks like in GeoQuery.class > setupQueries() the handle is not being returned successfully from the handles HashMap:

![44437711-d0e8e400-a5fe-11e8-89da-7bbb8d1e19bf](https://user-images.githubusercontent.com/15883575/44438639-5ec6ce00-a603-11e8-8b58-969d83e8ff25.png)

**Comment by TanapTheTimid** [comment]
I'm having the same problem

**Comment by cammace** [comment]
I opened a PR to check this, @theonlynick0430 can you look at it when you get a chance?

**Comment by dhruvshah1214** [comment]
Hey guys, thanks so much; sorry, that's our bad!

- Dhruv

**Comment by brendanosborne** [comment]
@dhruvshah1214 how can I get the fix? The version still seems to be 1.1.1 ?

**Comment by Marly1995** [comment]
@dhruvshah1214 Any news on a new version with this fix included? It seems to have been fixed but is not released.

**Comment by Supercaly** [comment]
Still getting this error settings the center and the radius
